Rework in Kotlin (#123)
* fix(generate-hashes): fix infrequent NPE

There is an edge-case where the rules are depending on each other's digests, but they're hashed in parallel, so threads will not see the result of a previous hashing iteration. To overcome this we synchronise access using ConcurrentHashMap for the ruleHashes

* fix(generate-hashes): attempt to fix the nested generatino deadlock

* fix(generate-hashes): fix recursing into already calculated hashes

* fix(generate-hashes): rework code a bit

* fix(generate-hashes): warn and fail on problems instead of masking the error

* feat(all): rewrite to kotlin

* separate concerns
* parallelise as much as possible
* rework CLI interface (generate-hashes is not a subcommand of root command really)
* remove redundant interfaces (there is only 1 implementation for each, no need for abstractions)
* preprocess arguments

* fix(test): bring back the tests

* feat(test): reimplement integration test

* fix(test): use just bazel instead of hardcoded path to bazel in e2e test

* fix(all): fix warnings

* feat(build): remove deprecated jcenter repository

* fix(ci): test logs and coverage report as an artifact

* separate matrix jobs into jre8 and jre11. JRE8 doesn't support coverage with the latest bazel (coverage reporter class is compiled for JRE11)
* latest upstream bazel breaks code coverage even for JRE11. use latest stable version

* fix(hashing): fix for NoSuchMethodError on ByteBuffer when running JRE9+ code on JRE8

* fix(ci): fix for bytebuddy mock macker